### ISSUE TITLE
Part replacements

### ISSUE THREAD

**Issue by HSBallina** [DunningtonAudio/258D#2]
Hi! I'm chasing down components for the 258d and 281d modules and have found most of them (a few still on backorder) but I have a hard time finding the MMBF5485 for the 258d. Do you have any suggestions for a replacement? DigiKey suggests the [SMMBFJ310LT1G](https://www.digikey.se/sv/products/detail/onsemi/SMMBFJ310LT1G/8538912) as a direct replacement but as far as I can see they're not a perfect match. Can you verify if they're close enough?

Thank you in advance :)

**Comment by DunningtonAudio** [comment]
It's probably close enough to work but I have not tested it. MMBFJ211 is close in spec and has been used in successful builds so that would be my first suggestion.
